version: '3.8'
services:
  postgres:
    image: postgres:15-alpine  
    environment:
      POSTGRES_USER: ScribeUser   
      POSTGRES_PASSWORD: CawffeeIsLove
      POSTGRES_DB: ScribeDB
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: 